
site:
  about:
    siteName: Krow
    siteDescription: A small library for generating tables in ASCII or HTML formats, built with Kotlin's type-safe builders

theme:
  social:
    github: 'copper-leaf/krow'
  primaryColor: '#449999'
  bannerColor: '#449999'
  menu:
  - type: 'link'
    title: 'Home'
    url: '#{$0|baseUrl}/'
  - type: 'wiki'
  - type: 'kotlindocClasses'
    title: 'Api Docs'
  trianglifyOptions:
    x_colors: ['#88ffe0', '#000000', '#88ffe0']
  useSidebarSearch: true

services:
  publications:
    stages:
      ghPages:
        branch: gh-pages
        latestDirName: latest
        publishType: CleanBranch
        username: copper-leaf
        repo: krow
